name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Hippius CLI ${{ github.ref_name }}
            
            ### Installation
            
            #### macOS
            ```bash
            brew install thenervelab/tap/hipc
            ```
            
            #### Ubuntu/Debian
            ```bash
            sudo dpkg -i hipc_${{ github.ref_name }}_amd64.deb
            ```
            
            #### From Source
            ```bash
            cargo install --git https://github.com/thenervelab/hippius-cli.git --tag ${{ github.ref }}
            ```

  build:
    name: Build ${{ matrix.target }}
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: hipc
            asset_name: hipc-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: hipc
            asset_name: hipc-${{ github.ref_name }}-x86_64-apple-darwin.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: hipc
            asset_name: hipc-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          cd -

      - name: Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}

  package:
    name: Create Debian Package
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install cargo-deb
        uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-deb

      - name: Build Debian Package
        run: cargo deb

      - name: Upload Debian Package
        uses: softprops/action-gh-release@v1
        with:
          files: target/debian/hipc_${{ github.ref_name }}_amd64.deb
